### ISSUE TITLE
remote containerに関して

### ISSUE THREAD

**Issue by shimamorieiki** [besna-institute/python_template#5]
以下の`devcontainer.json`の`"extensions"`が`remote container`の起動時にインストールされていない(ように見える)
他の人でも再現するか知りたい
```
  "extensions": [
    "editorconfig.editorconfig",
    "ms-python.python",
    "njpwerner.autodocstring"
  ]
```

**Comment by shimamorieiki** [comment]
`settings.json.default`の内容を`devcontainer.json`の`"settings"`に書けばいいような気がしているのだがそれではだめなのか

**Comment by nimiusrd** [comment]
ここで指摘されてる通りremote containerの設定はdevcontainer.json書けばOKなので，移動した
