### ISSUE TITLE
Pylint: R2004

### ISSUE THREAD

**Issue by ktr-skmt** [besna-institute/python_template#98]
R2004: Consider using a named constant or an enum instead of 'application/jsonl'. (magic-value-comparison)
https://github.com/besna-institute/python_template/blob/main/src/example/entrypoint.py#L21

次のように定数を用意して、
```python
JSONL_CONTENT_TYPE: Final[str] = "application/jsonl"
```
定数との等価比較をする
```python
    if request.content_type == JSONL_CONTENT_TYPE:
```

**Comment by nimiusrd** [comment]
R2004は消す

[Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) を入れる
